### ISSUE TITLE
Toonhud doesn't work with this

### ISSUE THREAD

**Issue by bobkinect98** [andy013/votehud_custom_font#10]
i think my main hud [toonhud](https://toonhud.com/) doesn't work with this
i did the steps that were listed to make it compatible with custom huds, but whenever i loaded up the game i just get flashbanged
![hl2_kB6Qilpbb7](https://user-images.githubusercontent.com/65422207/168944124-f735dab9-7121-4b03-89cd-592458c3c5cd.png)
and i tried to fix this myself by combining the "toonhud" folder with the "zzz_votehud_custom_font" folder, and replacing some text within the `clientscheme.res`. which fixed the flashbang issue, but then mysteriously the vote hud doesn't work when i tested it in a casual game, even though the files there.

**Comment by bobkinect98** [comment]
update
so the reason why the vote hud was "mysteriously not working" working was because a bot enhancement mod had a `chat_english.txt`, so i removed that temporarily just to test if the mod could finally work now
it worked, but its broken for some reason
and this is what he broken vote hud looked like
![image](https://user-images.githubusercontent.com/65422207/168946668-253963a3-0b0b-4b33-80c6-52866e5bc741.png)

**Comment by bobkinect98** [comment]
im a idiot
![image](https://user-images.githubusercontent.com/65422207/168965525-97297584-b4be-4c13-9d4a-1f277c0711ac.png)
it was just tf2bd with the "vote failed eraser" mod that was causing all of these issues
sorry for wasting your time

**Comment by andy013** [comment]
No worries, thanks for posting the solution. You should be able to copy and paste the required lines from this mods `chat_english.txt` file into the bot enhancement mods file of the same name if you want to run them both together.
