### ISSUE TITLE
The folder doesnt actually have to be named votehud_custom_font

### ISSUE THREAD

**Issue by Thespikedballofdoom** [andy013/votehud_custom_font#3]
I learned this while patching it into my clientscheme

It might be better to write to just copy the CUSTOM FONT MOD section in the clientscheme, cause it's way easier to put into the scheme than most people might suspect

**Comment by andy013** [comment]
Yes, I might add another line to the README to clarify this. Remember you also need to copy the custom font import at the very bottom of the file.

**Comment by andy013** [comment]
Also, I think the folder you copy the mod to must be named the same as the reference within the `info.vdf` file. If you have a custom HUD that already has this file then copying over into it's current folder should work fine.

**Comment by Thespikedballofdoom** [comment]
I cant get it to work properly when I pack it into a VPK, I don't know why

**Comment by andy013** [comment]
I don't think custom fonts work with VPK files unfortunately. See here: https://github.com/ValveSoftware/Source-1-Games/issues/338 The font wont work correctly if it's installed as a system font either. You just need to do it the old fashioned way with folders.

**Comment by Thespikedballofdoom** [comment]
![image](https://user-images.githubusercontent.com/43627353/113901111-86f7a100-979c-11eb-81b4-7dfc50e6965a.png)
