### ISSUE TITLE
How do you get it to work with custom fonts?

### ISSUE THREAD

**Issue by Sirbucket** [andy013/votehud_custom_font#4]
I've been trying to put in a patch for sunset HUD (Just testing atm) to have the symbols display while the default font that comes with the HUD is kept. I can't seem to get one with the other and just ends up looking strange.

**Comment by Sirbucket** [comment]
Is there a way to get the HUD to only recognize the symbols is the TLDR

**Comment by andy013** [comment]
No. You would need to create your own font for that to work. Is it a problem that this font is used instead? You shouldn't really be using this font outside of places where you need to identify bots trying to spoof other players.

**Comment by Sirbucket** [comment]
I was trying to see if I could use it to be implemented in every HUD to make it easier

**Comment by Sirbucket** [comment]
So like this is the source and then every HUD can use a piece of this to "patch" their HUD so it displays those symbols

**Comment by Sirbucket** [comment]
I was just wondering since you put in that it could be used in other huds, maybe explain that it can't be used with custom fonts as well

**Comment by Sirbucket** [comment]
I could def see a well designed anti bot hud by hypnotize using this as the base tho

**Comment by Sirbucket** [comment]
The problem was the noto sans itself was taking the place of the normal font of the HUD and I was trying to see if I could make it so it uses the symbols instead, I know understand what this HUDs purpose is though, it's a base for developing other HUDs around its font

**Comment by Sirbucket** [comment]
Still very cool and maybe I'll even try to design a HUD around it

**Comment by andy013** [comment]
I don't think its necessary to design a HUD around this. This was made with the intent that it could just be used as the voting UI without really affecting the rest of the HUD in any way. It's quite easy to just drop this into any HUD without changing much. The font in this shouldn't be replacing any other fonts outside of the voting panels.

If you post a screenshot or a repo with the custom HUD I might be able to better understand what you are trying to do.

**Comment by Sirbucket** [comment]
Odd, I couldn't get it to work then, cause when I'd join servers with name steal bots no symbols would appear when I tried it alongside other huds, maybe the bots are trying new symbols

**Comment by andy013** [comment]
I looked in your github history and saw you had a [commit](https://github.com/Hypnootize/Sunset-Hud/pull/8/commits/167d57f703ee4fb178bd5815bc50371e923a502c) to Sunset Hud using this. I know the commit was a mistake, but I noticed you copied incorrectly from my README file. What I had written there was just for illustration purposes. You had left 3 dots like this `...` that I put in place of all the other custom fonts. You aren't supposed to copy those over. It also looks like you closed the last curly brace too early and ended up cutting off 2 of the custom fonts that Sunset HUD uses. 

I have updated the README now with more instructions on how to combine this with other custom HUDS. I removed some of the confusing elements so now you should be able to just copy paste what's there. Give it another go and make sure you have the right number of curly braces and you paste into the right parts of the file. If you're still having trouble, let me know.
