### ISSUE TITLE
Font is blank after installing, while using with TF2 Bot Detector.

### ISSUE THREAD

**Issue by McHKS** [andy013/votehud_custom_font#8]
I do not see the name of the player being kicked after installing your files.  I have no custom HUDs.  I tried changing the override color, but no luck either.  Windows 10.
![ScreenshotKS](https://user-images.githubusercontent.com/92506027/137416742-359df181-3b74-45c2-96a0-f69eb6b28370.jpg)

**Comment by andy013** [comment]
It looks like it hasn't been installed correctly. Do you have any other custom folders or .vpk files that might be conflicting with it? Try deleting and downloading the mod files again. It looks like you might have not copied the `ui` folder within `resource` over or the directory structure is incorrect.

**Comment by McHKS** [comment]
Replaced 1.33 by overwriting files, and still the same.  Here's what's in my directories.
![Snip1](https://user-images.githubusercontent.com/92506027/137420693-78d12394-b008-4bb2-9e3e-fc56b3362ef1.JPG)
![snip2](https://user-images.githubusercontent.com/92506027/137420704-c2152785-3273-448b-a277-fb8fa501e80d.JPG)

**Comment by andy013** [comment]
Ah, I think the TF2 Bot Detector vote failed eraser is conflicting with this mods files. If you go into the Bot Detectors settings menu you can disable the mod and try it again.

![Untitled-2](https://user-images.githubusercontent.com/10728824/137420943-6c50f2a7-4d23-4ab4-8590-37a93893c784.png)

**Comment by McHKS** [comment]
That seemed to do it.  Thanks
