### ISSUE TITLE
missing char U+202C : POP DIRECTIONAL FORMATTING [PDF]

### ISSUE THREAD

**Issue by Thespikedballofdoom** [andy013/votehud_custom_font#9]
my friend jubz often gets hit by this. In action it doesn't show it as a white block

U+202C : POP DIRECTIONAL FORMATTING [PDF]

**Comment by andy013** [comment]
I tested this but can't reproduce it. The character displays as a solid box for me. Sometimes characters have zero width and can be drawn directly behind another character making it harder to see.

Here's what it looks like when I wrote the name "jubz" with 3 U+202C characters in between. 
![jubz](https://user-images.githubusercontent.com/10728824/156013477-7f6bd525-3513-47fe-86ec-42587a61ad0b.png)

You can test it by spawning a bot on your team on a local sever and giving the bot a name with the command `bot -team blue -name "‬ju‬bz‬"` then try and kick the bot. Sites like this one https://www.fileformat.info/info/unicode/char/202c/browsertest.htm allow you to copy and paste those invisible characters which makes it easier for testing.

**Comment by Thespikedballofdoom** [comment]
His name is actually : JUBZ and after I reinstalled the mod it works correctly. thanks for going through the effort to test it too

**Comment by andy013** [comment]
No worries, I might have missed that character in an older version of the font.
